import { NextResponse } from "next/server";
import { Listing } from "@/utils/index";

const data: Listing[] = [
  {
    name: "Johnson Group",
    address: "121 Andrew Drive\nSmithbury, AR 62613",
    category: "shared-stays",
    type: "guest-house",
    region: "Oceania",
    hourlyRate: 23874,
    amenities: [
      "Heating",
      "Parking",
      "Bar",
      "Room Service",
      "Restaurant",
      "Balcony",
    ],
  },
  {
    name: "Garcia-Willis",
    address: "2014 Kylie Ways Suite 356\nJamesville, MN 02353",
    category: "shared-stays",
    type: "roommates",
    region: "Africa",
    hourlyRate: 9464,
    amenities: ["WiFi", "Room Service", "Swimming Pool", "TV"],
  },
  {
    name: "Allen, Schaefer and Austin",
    address: "783 Frank Extension Apt. 356\nCampbellport, LA 61951",
    category: "shared-spaces",
    type: "hostel",
    region: "South America",
    hourlyRate: 15098,
    amenities: ["Air Conditioning", "Swimming Pool", "WiFi", "Laundry", "Bar"],
  },
  {
    name: "Roach, Donaldson and Stevenson",
    address: "25565 Darren Knolls\nEast Amanda, OK 64298",
    category: "shared-spaces",
    type: "hostel",
    region: "South America",
    hourlyRate: 29134,
    amenities: ["Conference Room", "Room Service", "Laundry"],
  },
  {
    name: "Christensen-Jones",
    address: "7904 Garcia Inlet\nWarrenfort, WI 77730",
    category: "shared-stays",
    type: "hostel",
    region: "Antarctica",
    hourlyRate: 49424,
    amenities: [
      "Gym",
      "WiFi",
      "Restaurant",
      "Conference Room",
      "Parking",
      "Heating",
    ],
  },
  {
    name: "Moss Group",
    address: "806 Palmer Port Apt. 203\nWest Justin, MD 58532",
    category: "share-time",
    type: "hotel",
    region: "Africa",
    hourlyRate: 13466,
    amenities: [
      "Conference Room",
      "TV",
      "Room Service",
      "Spa",
      "Airport Shuttle",
    ],
  },
  {
    name: "Barrett, Butler and Castaneda",
    address: "6043 Joanna Hill\nGinaberg, VA 71462",
    category: "shared-stays",
    type: "hostel",
    region: "South America",
    hourlyRate: 39767,
    amenities: [
      "WiFi",
      "Pet Friendly",
      "Heating",
      "Air Conditioning",
      "TV",
      "Breakfast Included",
    ],
  },
  {
    name: "Wilson-Petty",
    address: "117 Abigail Spring\nHoffmanton, MO 74773",
    category: "shared-stays",
    type: "roommates",
    region: "Asia",
    hourlyRate: 92084,
    amenities: ["Restaurant", "Air Conditioning", "Parking", "Airport Shuttle"],
  },
  {
    name: "Underwood PLC",
    address: "723 Kimberly Forges Suite 147\nNew Katieshire, MD 73112",
    category: "shared-stays",
    type: "roommates",
    region: "Oceania",
    hourlyRate: 38011,
    amenities: ["Heating", "Balcony", "Kitchen", "TV", "Parking"],
  },
  {
    name: "Bailey Ltd",
    address: "669 James Road Suite 209\nNorth Stephen, KY 79015",
    category: "share-time",
    type: "hotel",
    region: "Asia",
    hourlyRate: 3693,
    amenities: ["Balcony", "Restaurant", "Spa"],
  },
  {
    name: "Rhodes Ltd",
    address: "5230 Chavez Junctions Suite 139\nEast Sherry, VA 45648",
    category: "shared-stays",
    type: "guest-house",
    region: "Africa",
    hourlyRate: 37288,
    amenities: [
      "Room Service",
      "Breakfast Included",
      "Gym",
      "Spa",
      "Restaurant",
      "Parking",
      "Bar",
    ],
  },
  {
    name: "Sullivan and Sons",
    address: "73473 James Valleys Suite 929\nWest Whitney, ND 89774",
    category: "share-time",
    type: "hostel",
    region: "Asia",
    hourlyRate: 53025,
    amenities: [
      "Kitchen",
      "Swimming Pool",
      "Conference Room",
      "Gym",
      "Laundry",
      "Restaurant",
    ],
  },
  {
    name: "Miller, Watts and Brown",
    address: "799 Kathy Ridge Apt. 768\nJeffreybury, OK 50763",
    category: "shared-stays",
    type: "roommates",
    region: "Oceania",
    hourlyRate: 62737,
    amenities: ["Gym", "Laundry", "Room Service", "TV"],
  },
  {
    name: "Oneal, Dunlap and Ramsey",
    address: "4021 Brown Mission Suite 984\nPaynemouth, OK 05099",
    category: "share-time",
    type: "roommates",
    region: "Oceania",
    hourlyRate: 32460,
    amenities: ["Breakfast Included", "Laundry", "Balcony", "Gym"],
  },
  {
    name: "Smith, Cole and Taylor",
    address: "7894 Robinson Causeway\nJessetown, WV 85455",
    category: "share-time",
    type: "hostel",
    region: "Europe",
    hourlyRate: 1692,
    amenities: ["Heating", "Airport Shuttle", "WiFi", "Air Conditioning"],
  },
  {
    name: "Hernandez-Ray",
    address: "000 Timothy Neck\nNew Julieland, KS 31353",
    category: "shared-spaces",
    type: "hourly-room",
    region: "Europe",
    hourlyRate: 74788,
    amenities: [
      "Conference Room",
      "Bar",
      "Gym",
      "Swimming Pool",
      "Heating",
      "WiFi",
    ],
  },
  {
    name: "Pace Ltd",
    address: "99016 Velez Vista\nSamanthamouth, MN 53715",
    category: "share-time",
    type: "hotel",
    region: "Antarctica",
    hourlyRate: 44031,
    amenities: [
      "TV",
      "Swimming Pool",
      "WiFi",
      "Room Service",
      "Breakfast Included",
      "Air Conditioning",
      "Restaurant",
    ],
  },
  {
    name: "Bowen, May and Simpson",
    address: "298 Kara Cliff\nLake Williamport, IL 77989",
    category: "shared-spaces",
    type: "roommates",
    region: "Africa",
    hourlyRate: 87944,
    amenities: ["Balcony", "Swimming Pool", "Air Conditioning", "TV"],
  },
  {
    name: "Keith-Thomas",
    address: "3813 Victoria Ridge\nNorth Joanborough, WI 76058",
    category: "shared-spaces",
    type: "hourly-room",
    region: "Africa",
    hourlyRate: 38669,
    amenities: ["Room Service", "Breakfast Included", "WiFi", "Heating"],
  },
  {
    name: "Hurst-Young",
    address: "11783 Justin Vista\nUnderwoodshire, CT 16743",
    category: "share-time",
    type: "roommates",
    region: "South America",
    hourlyRate: 5278,
    amenities: ["Conference Room", "Kitchen", "Breakfast Included"],
  },
  {
    name: "Vasquez-Wagner",
    address: "76123 Quinn Roads\nNorth Danielle, OK 75755",
    category: "share-time",
    type: "roommates",
    region: "Europe",
    hourlyRate: 69239,
    amenities: ["Restaurant", "Airport Shuttle", "Heating"],
  },
  {
    name: "Allen and Sons",
    address: "257 Wilkinson Views\nFigueroamouth, IA 30978",
    category: "share-time",
    type: "guest-house",
    region: "Africa",
    hourlyRate: 10672,
    amenities: ["Pet Friendly", "Swimming Pool", "Parking"],
  },
  {
    name: "Brooks, Smith and Holmes",
    address: "4119 Hart Lights Suite 212\nWest Patrick, SD 29809",
    category: "share-time",
    type: "hostel",
    region: "Oceania",
    hourlyRate: 62333,
    amenities: ["Gym", "Swimming Pool", "Restaurant", "Bar"],
  },
  {
    name: "Stone PLC",
    address: "2736 Ana Spring\nSellersville, NM 63936",
    category: "shared-stays",
    type: "roommates",
    region: "Asia",
    hourlyRate: 84285,
    amenities: [
      "Gym",
      "Room Service",
      "Restaurant",
      "Pet Friendly",
      "Conference Room",
      "Airport Shuttle",
    ],
  },
  {
    name: "Miller, Burns and Gutierrez",
    address: "8467 Smith Burg\nEast Cherylville, VA 22615",
    category: "share-time",
    type: "guest-house",
    region: "Asia",
    hourlyRate: 59302,
    amenities: [
      "WiFi",
      "Laundry",
      "Gym",
      "Conference Room",
      "Heating",
      "Airport Shuttle",
    ],
  },
  {
    name: "Perkins LLC",
    address: "44476 Misty Mews Apt. 917\nChandlermouth, ME 53561",
    category: "shared-spaces",
    type: "hourly-room",
    region: "Europe",
    hourlyRate: 96153,
    amenities: [
      "Restaurant",
      "Heating",
      "Parking",
      "Pet Friendly",
      "Airport Shuttle",
      "Conference Room",
    ],
  },
  {
    name: "Herman LLC",
    address: "529 Lauren Square\nJonesland, TN 35141",
    category: "shared-spaces",
    type: "hotel",
    region: "Antarctica",
    hourlyRate: 7441,
    amenities: ["Gym", "Bar", "Air Conditioning"],
  },
  {
    name: "Robinson Group",
    address: "367 Johnson Bypass Suite 893\nWest Melodyland, DE 73670",
    category: "shared-spaces",
    type: "hostel",
    region: "Europe",
    hourlyRate: 55505,
    amenities: ["Airport Shuttle", "TV", "WiFi", "Heating", "Laundry"],
  },
  {
    name: "Smith PLC",
    address: "867 Diaz Ramp Apt. 100\nJosephtown, CO 91173",
    category: "share-time",
    type: "hostel",
    region: "Africa",
    hourlyRate: 37004,
    amenities: ["Gym", "Swimming Pool", "Spa"],
  },
  {
    name: "Anderson-Cooper",
    address: "66609 Charles Glens\nNew Dylan, MT 72811",
    category: "share-time",
    type: "roommates",
    region: "Antarctica",
    hourlyRate: 73809,
    amenities: ["Balcony", "Air Conditioning", "Conference Room", "Restaurant"],
  },
  {
    name: "Juarez, Burns and Williams",
    address: "13382 Monica Fork\nTaraburgh, SC 40473",
    category: "shared-stays",
    type: "hourly-room",
    region: "North America",
    hourlyRate: 45047,
    amenities: [
      "Gym",
      "Heating",
      "Air Conditioning",
      "Pet Friendly",
      "Room Service",
      "Swimming Pool",
      "WiFi",
    ],
  },
  {
    name: "Baker-Mccann",
    address: "29948 Torres Stravenue Apt. 544\nMichellemouth, AR 84149",
    category: "share-time",
    type: "guest-house",
    region: "Antarctica",
    hourlyRate: 37129,
    amenities: ["TV", "Bar", "Balcony", "Parking"],
  },
  {
    name: "Manning-White",
    address: "164 Warren Road Suite 609\nEast Amandafurt, NJ 99944",
    category: "shared-stays",
    type: "hotel",
    region: "North America",
    hourlyRate: 87851,
    amenities: [
      "Balcony",
      "Room Service",
      "Laundry",
      "Swimming Pool",
      "Heating",
      "Gym",
    ],
  },
  {
    name: "Henry, Bender and Espinoza",
    address: "1952 Rogers Roads\nEast Eric, NM 44495",
    category: "shared-spaces",
    type: "hostel",
    region: "Europe",
    hourlyRate: 5935,
    amenities: ["Swimming Pool", "Pet Friendly", "Heating"],
  },
  {
    name: "Good LLC",
    address: "5775 Theresa Circles Suite 358\nMichaelhaven, WY 42798",
    category: "shared-stays",
    type: "hostel",
    region: "Africa",
    hourlyRate: 86925,
    amenities: [
      "Swimming Pool",
      "Balcony",
      "Air Conditioning",
      "TV",
      "Kitchen",
    ],
  },
  {
    name: "Sawyer, Vega and Johnson",
    address: "002 Mason Forest Suite 339\nCaitlinstad, IA 95305",
    category: "shared-stays",
    type: "hourly-room",
    region: "South America",
    hourlyRate: 49148,
    amenities: ["Parking", "Spa", "Air Conditioning", "Heating"],
  },
  {
    name: "Nelson and Sons",
    address: "985 Gray Rapid Apt. 638\nSouth Stephanie, VA 65903",
    category: "shared-spaces",
    type: "hostel",
    region: "Europe",
    hourlyRate: 68715,
    amenities: ["Airport Shuttle", "TV", "Gym"],
  },
  {
    name: "Rodriguez, Leonard and Cantrell",
    address: "111 Michael Grove\nFrankton, AL 37899",
    category: "shared-stays",
    type: "guest-house",
    region: "South America",
    hourlyRate: 94574,
    amenities: [
      "Pet Friendly",
      "Laundry",
      "TV",
      "Gym",
      "WiFi",
      "Balcony",
      "Heating",
    ],
  },
  {
    name: "Duran, Ford and Frank",
    address: "PSC 9036, Box 9718\nAPO AA 74517",
    category: "shared-spaces",
    type: "roommates",
    region: "Africa",
    hourlyRate: 90153,
    amenities: ["Laundry", "Room Service", "Bar"],
  },
  {
    name: "Perkins-Jones",
    address: "0665 Brown Knoll Apt. 225\nSouth Bobby, DC 55156",
    category: "share-time",
    type: "hostel",
    region: "North America",
    hourlyRate: 1087,
    amenities: ["Restaurant", "Kitchen", "Pet Friendly", "Balcony", "Heating"],
  },
  {
    name: "Wilson-Turner",
    address: "5435 Crystal Track Apt. 785\nPort Matthewville, KS 81092",
    category: "shared-stays",
    type: "hourly-room",
    region: "South America",
    hourlyRate: 30359,
    amenities: [
      "Airport Shuttle",
      "WiFi",
      "Conference Room",
      "Gym",
      "Swimming Pool",
      "Laundry",
      "Pet Friendly",
    ],
  },
  {
    name: "Pearson-Ortiz",
    address: "88674 Richard Corner\nSouth Gail, IA 84689",
    category: "shared-spaces",
    type: "hotel",
    region: "Asia",
    hourlyRate: 51961,
    amenities: [
      "Parking",
      "Balcony",
      "Restaurant",
      "Room Service",
      "Kitchen",
      "Spa",
    ],
  },
  {
    name: "Williams-Chaney",
    address: "3364 Cooper Lodge\nLake Sharon, MO 56727",
    category: "shared-spaces",
    type: "hostel",
    region: "Europe",
    hourlyRate: 43149,
    amenities: ["Pet Friendly", "Parking", "Room Service", "Air Conditioning"],
  },
  {
    name: "Vance and Sons",
    address: "Unit 9119 Box 9639\nDPO AE 67130",
    category: "shared-spaces",
    type: "hotel",
    region: "Europe",
    hourlyRate: 44417,
    amenities: [
      "WiFi",
      "Spa",
      "Parking",
      "Heating",
      "Kitchen",
      "Air Conditioning",
    ],
  },
  {
    name: "Martinez Group",
    address: "78879 Carrillo Valleys\nNew Danielburgh, DE 85610",
    category: "share-time",
    type: "hotel",
    region: "Europe",
    hourlyRate: 45386,
    amenities: ["Restaurant", "Bar", "Gym", "Kitchen"],
  },
  {
    name: "Williams LLC",
    address: "424 Obrien Land Apt. 272\nSouth Amanda, NH 99850",
    category: "shared-stays",
    type: "guest-house",
    region: "Africa",
    hourlyRate: 53256,
    amenities: ["Pet Friendly", "Heating", "TV", "WiFi"],
  },
  {
    name: "Mejia PLC",
    address: "086 Larson Points Apt. 292\nBerryton, VA 96488",
    category: "shared-stays",
    type: "guest-house",
    region: "Antarctica",
    hourlyRate: 45474,
    amenities: ["Balcony", "Spa", "Bar", "WiFi", "Parking", "Conference Room"],
  },
  {
    name: "Joyce, Logan and Hood",
    address: "891 Lane Alley\nEast Andrea, FL 42633",
    category: "shared-spaces",
    type: "guest-house",
    region: "South America",
    hourlyRate: 77602,
    amenities: [
      "Swimming Pool",
      "Airport Shuttle",
      "Spa",
      "Balcony",
      "WiFi",
      "TV",
      "Bar",
    ],
  },
  {
    name: "Rocha-Black",
    address: "95284 Johnson Coves Apt. 355\nWest Laurie, FL 78521",
    category: "shared-spaces",
    type: "hourly-room",
    region: "Africa",
    hourlyRate: 80203,
    amenities: ["Bar", "Air Conditioning", "Laundry", "Spa", "Airport Shuttle"],
  },
  {
    name: "Hill Ltd",
    address: "90721 Samantha Brook Suite 693\nBurnshaven, WA 61961",
    category: "share-time",
    type: "roommates",
    region: "North America",
    hourlyRate: 77715,
    amenities: [
      "Parking",
      "Restaurant",
      "Spa",
      "TV",
      "Conference Room",
      "Airport Shuttle",
      "Pet Friendly",
    ],
  },
  {
    name: "Burns Ltd",
    address: "52013 Pugh Pine Apt. 420\nPort Danny, WY 24164",
    category: "share-time",
    type: "roommates",
    region: "Africa",
    hourlyRate: 18764,
    amenities: ["Breakfast Included", "TV", "Spa", "Laundry"],
  },
  {
    name: "Gibbs-Erickson",
    address: "93430 Horne Ports Suite 046\nPort Jennifer, MO 15698",
    category: "shared-spaces",
    type: "guest-house",
    region: "Europe",
    hourlyRate: 15577,
    amenities: ["Swimming Pool", "Spa", "Airport Shuttle", "Parking"],
  },
  {
    name: "Roberts-Sullivan",
    address: "50229 George Ville Apt. 069\nBrownland, CT 68110",
    category: "share-time",
    type: "guest-house",
    region: "Asia",
    hourlyRate: 65936,
    amenities: [
      "Balcony",
      "WiFi",
      "Conference Room",
      "Laundry",
      "Gym",
      "Airport Shuttle",
      "Kitchen",
    ],
  },
  {
    name: "Miller-Tran",
    address: "74049 Tracy Run\nDiazmouth, HI 61571",
    category: "share-time",
    type: "hotel",
    region: "Europe",
    hourlyRate: 9918,
    amenities: ["Parking", "Pet Friendly", "Bar"],
  },
  {
    name: "Francis Inc",
    address: "414 Powell Prairie\nYolandastad, SD 11856",
    category: "share-time",
    type: "guest-house",
    region: "North America",
    hourlyRate: 5221,
    amenities: [
      "WiFi",
      "Airport Shuttle",
      "Heating",
      "Parking",
      "Restaurant",
      "Laundry",
      "Pet Friendly",
    ],
  },
  {
    name: "Murphy and Sons",
    address: "702 Sarah Neck\nWest Jenniferfort, CT 85610",
    category: "shared-stays",
    type: "hostel",
    region: "Antarctica",
    hourlyRate: 47066,
    amenities: ["Balcony", "Swimming Pool", "Spa"],
  },
  {
    name: "Johnson LLC",
    address: "7064 Victoria Spurs Apt. 674\nCarterland, LA 10686",
    category: "shared-stays",
    type: "hourly-room",
    region: "Oceania",
    hourlyRate: 7866,
    amenities: ["Breakfast Included", "Parking", "Heating", "Air Conditioning"],
  },
  {
    name: "Silva LLC",
    address: "19770 Leonard Village\nEast Justin, ME 63475",
    category: "share-time",
    type: "hostel",
    region: "Europe",
    hourlyRate: 37257,
    amenities: ["Airport Shuttle", "Air Conditioning", "TV", "Gym", "Laundry"],
  },
  {
    name: "Hunt-Schultz",
    address: "32925 Amy Course Suite 322\nAguilarmouth, KY 99328",
    category: "shared-spaces",
    type: "guest-house",
    region: "Oceania",
    hourlyRate: 96894,
    amenities: ["Air Conditioning", "Bar", "Kitchen", "Breakfast Included"],
  },
  {
    name: "Bates-Mason",
    address: "9959 Barton Junctions\nPort Megan, WA 58230",
    category: "share-time",
    type: "hostel",
    region: "Asia",
    hourlyRate: 58464,
    amenities: ["Breakfast Included", "Gym", "Balcony"],
  },
  {
    name: "Kirby, Adams and Hester",
    address: "314 Jones Road Apt. 403\nEast Colleen, TX 62211",
    category: "share-time",
    type: "guest-house",
    region: "Oceania",
    hourlyRate: 16366,
    amenities: ["Parking", "Kitchen", "Laundry", "TV", "Conference Room"],
  },
  {
    name: "Miranda, Sanchez and Stewart",
    address: "11819 Castillo Avenue Suite 595\nSchneidershire, SD 01328",
    category: "share-time",
    type: "hourly-room",
    region: "Europe",
    hourlyRate: 36909,
    amenities: ["Spa", "Swimming Pool", "Balcony", "Laundry", "Restaurant"],
  },
  {
    name: "Porter-Burgess",
    address: "14161 Allison Ranch Suite 273\nStephaniemouth, WY 24021",
    category: "share-time",
    type: "guest-house",
    region: "Asia",
    hourlyRate: 95355,
    amenities: [
      "Heating",
      "Air Conditioning",
      "Balcony",
      "WiFi",
      "Breakfast Included",
      "Laundry",
    ],
  },
  {
    name: "Moore-Edwards",
    address: "346 Johnson Divide\nThompsonfurt, NH 89217",
    category: "shared-stays",
    type: "hourly-room",
    region: "Oceania",
    hourlyRate: 77133,
    amenities: ["Airport Shuttle", "Laundry", "Kitchen"],
  },
  {
    name: "Bailey-Humphrey",
    address: "1065 Kara Crest\nBrockborough, MO 62256",
    category: "shared-spaces",
    type: "hotel",
    region: "South America",
    hourlyRate: 38040,
    amenities: ["WiFi", "Conference Room", "Breakfast Included"],
  },
  {
    name: "Gonzalez and Sons",
    address: "277 Dawn Mountains\nNorth Amber, WY 45302",
    category: "shared-spaces",
    type: "hourly-room",
    region: "South America",
    hourlyRate: 66507,
    amenities: [
      "WiFi",
      "Kitchen",
      "Heating",
      "Swimming Pool",
      "Laundry",
      "Breakfast Included",
      "Air Conditioning",
    ],
  },
  {
    name: "Ruiz, Moore and Wilson",
    address: "2767 Douglas Well\nNew Deanna, ND 71527",
    category: "shared-spaces",
    type: "roommates",
    region: "North America",
    hourlyRate: 82465,
    amenities: [
      "Room Service",
      "Gym",
      "Bar",
      "Parking",
      "Kitchen",
      "WiFi",
      "Heating",
    ],
  },
  {
    name: "Carr, Roman and Hamilton",
    address: "29369 Kenneth Ports Suite 413\nSouth Benjaminbury, VA 07910",
    category: "shared-stays",
    type: "hotel",
    region: "South America",
    hourlyRate: 87927,
    amenities: [
      "Gym",
      "Conference Room",
      "Room Service",
      "Air Conditioning",
      "Kitchen",
      "Breakfast Included",
      "Parking",
    ],
  },
  {
    name: "Goodman Ltd",
    address: "235 Hickman Mews Suite 560\nRodriguezmouth, VT 21085",
    category: "shared-spaces",
    type: "guest-house",
    region: "North America",
    hourlyRate: 59937,
    amenities: ["Gym", "Spa", "Swimming Pool", "Breakfast Included"],
  },
  {
    name: "Campos Inc",
    address: "77329 Robinson Port\nEast Kylieview, VA 26449",
    category: "share-time",
    type: "guest-house",
    region: "Asia",
    hourlyRate: 20260,
    amenities: [
      "Restaurant",
      "Conference Room",
      "Heating",
      "Spa",
      "Room Service",
      "Pet Friendly",
    ],
  },
  {
    name: "Hines-Bush",
    address: "Unit 3786 Box 2094\nDPO AA 90806",
    category: "shared-stays",
    type: "hostel",
    region: "South America",
    hourlyRate: 6718,
    amenities: ["TV", "Heating", "Conference Room"],
  },
  {
    name: "Obrien Ltd",
    address: "4227 Mason Club Suite 247\nFranklinville, MS 80300",
    category: "shared-spaces",
    type: "hourly-room",
    region: "Asia",
    hourlyRate: 69280,
    amenities: ["Parking", "Breakfast Included", "Conference Room", "Bar"],
  },
  {
    name: "Mitchell, Smith and Martin",
    address: "62488 Jacobs Villages\nWaltontown, NM 56904",
    category: "share-time",
    type: "hotel",
    region: "Oceania",
    hourlyRate: 4844,
    amenities: [
      "Gym",
      "Air Conditioning",
      "Balcony",
      "Breakfast Included",
      "Pet Friendly",
    ],
  },
  {
    name: "Cole, Shepherd and Wilson",
    address: "Unit 5085 Box 8700\nDPO AP 22368",
    category: "share-time",
    type: "roommates",
    region: "North America",
    hourlyRate: 23234,
    amenities: [
      "Heating",
      "Balcony",
      "Kitchen",
      "WiFi",
      "Air Conditioning",
      "Laundry",
    ],
  },
  {
    name: "Williams-Abbott",
    address: "014 Martinez Common\nPort Angela, LA 62968",
    category: "shared-stays",
    type: "hourly-room",
    region: "North America",
    hourlyRate: 11715,
    amenities: [
      "Air Conditioning",
      "Laundry",
      "TV",
      "Bar",
      "Restaurant",
      "Kitchen",
      "Room Service",
    ],
  },
  {
    name: "Palmer and Sons",
    address: "04068 Townsend Crest\nSummerchester, HI 45048",
    category: "share-time",
    type: "hotel",
    region: "South America",
    hourlyRate: 75246,
    amenities: ["Pet Friendly", "Balcony", "Gym", "Parking"],
  },
  {
    name: "Swanson, Michael and Hamilton",
    address: "5770 Thomas Village Suite 589\nBillyfort, WI 47606",
    category: "share-time",
    type: "hostel",
    region: "Antarctica",
    hourlyRate: 2877,
    amenities: ["Room Service", "Gym", "Breakfast Included"],
  },
  {
    name: "Blake LLC",
    address: "513 Joseph Lake\nLake Adam, VT 13572",
    category: "share-time",
    type: "hostel",
    region: "North America",
    hourlyRate: 43336,
    amenities: ["Kitchen", "Air Conditioning", "Spa", "Heating"],
  },
  {
    name: "Terry and Sons",
    address: "0685 Oscar Estate\nLake Nicole, NE 37885",
    category: "shared-stays",
    type: "roommates",
    region: "North America",
    hourlyRate: 73370,
    amenities: ["Bar", "Laundry", "Room Service", "Spa"],
  },
  {
    name: "Avila Ltd",
    address: "860 Brianna Fields Apt. 970\nLake Joseph, DE 14444",
    category: "share-time",
    type: "hotel",
    region: "South America",
    hourlyRate: 12498,
    amenities: ["Swimming Pool", "TV", "Bar", "Pet Friendly"],
  },
  {
    name: "Sharp Ltd",
    address: "43072 Bautista Cove\nTorreschester, NE 22841",
    category: "shared-spaces",
    type: "hotel",
    region: "Africa",
    hourlyRate: 27408,
    amenities: ["Kitchen", "Pet Friendly", "Bar", "WiFi"],
  },
  {
    name: "Perry Inc",
    address: "57408 Jones Trace\nDorishaven, AR 60651",
    category: "shared-stays",
    type: "hostel",
    region: "Africa",
    hourlyRate: 8770,
    amenities: [
      "Gym",
      "Air Conditioning",
      "Balcony",
      "Conference Room",
      "Restaurant",
      "Airport Shuttle",
    ],
  },
  {
    name: "Peterson-Vaughn",
    address: "97528 Gerald Field\nNorth Billy, MN 04043",
    category: "shared-spaces",
    type: "hotel",
    region: "Asia",
    hourlyRate: 14695,
    amenities: ["Kitchen", "Air Conditioning", "Gym"],
  },
  {
    name: "Vance, Miller and Hunter",
    address: "21558 Debra Neck\nJuanbury, NV 40514",
    category: "share-time",
    type: "guest-house",
    region: "Antarctica",
    hourlyRate: 95788,
    amenities: [
      "WiFi",
      "Airport Shuttle",
      "Restaurant",
      "TV",
      "Swimming Pool",
      "Gym",
      "Laundry",
    ],
  },
  {
    name: "Davidson-Bird",
    address: "1159 Whitehead Circle\nPerryland, AR 93403",
    category: "shared-spaces",
    type: "hotel",
    region: "South America",
    hourlyRate: 69290,
    amenities: [
      "Swimming Pool",
      "Conference Room",
      "Heating",
      "Balcony",
      "Airport Shuttle",
      "Restaurant",
      "Air Conditioning",
    ],
  },
  {
    name: "Carpenter Inc",
    address: "8400 Williams Inlet Suite 038\nEast Kaitlin, ND 12423",
    category: "share-time",
    type: "hourly-room",
    region: "North America",
    hourlyRate: 58545,
    amenities: [
      "Gym",
      "Restaurant",
      "WiFi",
      "Conference Room",
      "TV",
      "Air Conditioning",
      "Room Service",
    ],
  },
  {
    name: "Johnson and Sons",
    address: "85141 Kathleen Mount Suite 282\nNorth Shannon, WY 55485",
    category: "share-time",
    type: "roommates",
    region: "Europe",
    hourlyRate: 25608,
    amenities: ["Room Service", "Swimming Pool", "Airport Shuttle"],
  },
  {
    name: "Jones, Fleming and Ellis",
    address: "556 Kaitlyn Orchard\nMcphersonport, CT 12971",
    category: "shared-spaces",
    type: "hourly-room",
    region: "North America",
    hourlyRate: 44360,
    amenities: ["Restaurant", "Pet Friendly", "Spa", "Laundry"],
  },
  {
    name: "Young, Williams and Warner",
    address: "051 Hammond Summit Suite 968\nWest Nicole, CO 92318",
    category: "shared-spaces",
    type: "hostel",
    region: "Asia",
    hourlyRate: 57531,
    amenities: [
      "Breakfast Included",
      "Laundry",
      "Airport Shuttle",
      "Pet Friendly",
      "Spa",
    ],
  },
  {
    name: "Collins, Rios and Elliott",
    address: "31872 Nicole Gardens Apt. 271\nEast Joseph, MA 86826",
    category: "share-time",
    type: "guest-house",
    region: "Africa",
    hourlyRate: 67170,
    amenities: [
      "Restaurant",
      "Parking",
      "TV",
      "Conference Room",
      "Balcony",
      "Breakfast Included",
      "Room Service",
    ],
  },
  {
    name: "Simpson Ltd",
    address: "5925 Andrea Road Apt. 145\nRamirezmouth, KY 38626",
    category: "shared-stays",
    type: "hourly-room",
    region: "Oceania",
    hourlyRate: 99085,
    amenities: ["Air Conditioning", "Breakfast Included", "Spa"],
  },
  {
    name: "Allen, Montgomery and Sosa",
    address: "35228 Meyers Radial\nSouth Matthewside, SC 94406",
    category: "share-time",
    type: "roommates",
    region: "Oceania",
    hourlyRate: 81950,
    amenities: ["Parking", "Balcony", "WiFi", "Swimming Pool"],
  },
  {
    name: "Smith, Santos and Keller",
    address: "64629 Katherine Burg\nGregoryview, LA 63422",
    category: "shared-spaces",
    type: "guest-house",
    region: "Europe",
    hourlyRate: 86598,
    amenities: ["Pet Friendly", "Spa", "Conference Room", "Parking", "TV"],
  },
  {
    name: "Miller Inc",
    address: "95244 Allen Mills Apt. 949\nSouth Crystalbury, VT 39834",
    category: "share-time",
    type: "hourly-room",
    region: "Asia",
    hourlyRate: 1854,
    amenities: ["Gym", "Balcony", "Airport Shuttle"],
  },
  {
    name: "Brown-Mason",
    address: "Unit 7541 Box 2489\nDPO AE 04000",
    category: "shared-spaces",
    type: "hostel",
    region: "South America",
    hourlyRate: 57658,
    amenities: [
      "Conference Room",
      "Air Conditioning",
      "Airport Shuttle",
      "Pet Friendly",
    ],
  },
  {
    name: "Johnson-Stevenson",
    address: "415 Robinson Ways\nStephanieton, MN 57667",
    category: "shared-spaces",
    type: "hostel",
    region: "Europe",
    hourlyRate: 1304,
    amenities: ["Airport Shuttle", "Bar", "Swimming Pool"],
  },
  {
    name: "Ward Ltd",
    address: "026 Rogers Turnpike\nNorth Monique, WI 47457",
    category: "shared-spaces",
    type: "guest-house",
    region: "North America",
    hourlyRate: 19863,
    amenities: [
      "Conference Room",
      "Breakfast Included",
      "Air Conditioning",
      "Balcony",
    ],
  },
  {
    name: "Mckay, Jimenez and Hale",
    address: "100 Lance Village Apt. 802\nEast Kaylastad, ID 24285",
    category: "shared-stays",
    type: "guest-house",
    region: "Africa",
    hourlyRate: 86122,
    amenities: [
      "Pet Friendly",
      "Breakfast Included",
      "Air Conditioning",
      "TV",
      "Spa",
      "Restaurant",
      "Parking",
    ],
  },
  {
    name: "Kim PLC",
    address: "035 Crawford Fords Apt. 630\nWest Markstad, MS 74322",
    category: "shared-stays",
    type: "hostel",
    region: "South America",
    hourlyRate: 74432,
    amenities: [
      "Spa",
      "Balcony",
      "Room Service",
      "Bar",
      "Conference Room",
      "Airport Shuttle",
    ],
  },
  {
    name: "Payne LLC",
    address: "293 Benjamin Trace Suite 746\nKleinville, IA 79610",
    category: "shared-spaces",
    type: "hostel",
    region: "Oceania",
    hourlyRate: 9001,
    amenities: ["WiFi", "Balcony", "Pet Friendly", "Spa", "Kitchen"],
  },
];

export async function GET(
  request: Request,
  { params }: { params: { category: string } }
) {
  const { category } = await params;

  try {
    const filteredListings: Listing[] = data.filter(
      (listing) => listing.category === category
    );

    return NextResponse.json({
      success: true,
      data: filteredListings,
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch listings",
      },
      { status: 500 }
    );
  }
}
